/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-08-25 08:43:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!------ Start Footer ------->\r\n");
      out.write("                <div class=\"row footer\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"footer-parts\">\r\n");
      out.write("                            <div class=\"footer-parts-h4\">About Us</div>\r\n");
      out.write("                            <div class=\"about-footer\">Lorem Ipsum is simply dummy text of the printing and typesetting industry. \r\n");
      out.write("                                Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"footer-parts\">\r\n");
      out.write("                            <div class=\"footer-parts-h4\">Extra Links</div>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Careers</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Terms &amp; Conditions</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"footer-parts\">\r\n");
      out.write("                            <div class=\"footer-parts-h4\">Extra Links</div>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Diclimer</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("                        <div class=\"footer-parts\">\r\n");
      out.write("                            <div class=\"footer-parts-h4\">Social Links</div><br />\r\n");
      out.write("                            <div style=\"padding-left:20px; font-size:22px;\">\r\n");
      out.write("                                <a href=\"https://www.facebook.com/freetimelearn/\" target=\"_blank\"><i class=\"fa fa-facebook fa_footer\"></i></a> &nbsp; &nbsp;\r\n");
      out.write("                                <a href=\"https://www.linkedin.com/in/free-time-learn-07598b143/\" target=\"_blank\"><i class=\"fa fa-linkedin fa_footer\"></i></a> &nbsp; &nbsp;\r\n");
      out.write("                                <a href=\"https://twitter.com/freetimelearn\" target=\"_blank\"><i class=\"fa fa-twitter fa_footer\"></i></a> &nbsp; &nbsp;\r\n");
      out.write("                                <a href=\"https://plus.google.com/101612697119159092378\" target=\"_blank\"><i class=\"fa fa-google-plus fa_footer\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div style=\"padding-left:20px; padding-top:15px; font-size:22px;\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" placeholder=\"Subscribe Now\">\r\n");
      out.write("                                    <span class=\"input-group-btn\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn btn_search\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div><br />\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("                    <div class=\"copyrights\">\r\n");
      out.write("                        <div class=\"col-md-8 col-sm-8 col-xs-12\">\r\n");
      out.write("                            <div class=\"copyrights-left\">\r\n");
      out.write("                                &copy; 2018. All rights reserved by <a href=\"http://www.freetimelearning.com\" target=\"_blank\">Free Time Learn</a>.\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                            <div class=\"copyrights-right\">\r\n");
      out.write("                                Designed by <a href=\"http://www.freetimelearning.com\" target=\"_blank\">F T L</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
